[package]
name = "md-terminal-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termcolor = "1.1"
markdown = { version = "1.0.0-alpha.20", features = ["json"] }
syntect = { version = "5.2.0", features = [
  "parsing",
  "regex-fancy",
  "default-themes",
  "default-syntaxes",
] }
